Global:
  model_dir: save_quant_inception
  model_filename: inference.pdmodel
  params_filename: inference.pdiparams
  batch_size: 32
  resize_size: 320
  img_size: 299
  data_dir: ./ILSVRC2012
  
Distillation:
  alpha: 1.0
  loss: l2
  node:
  - softmax_1.tmp_0
Quantization:
  is_full_quantize: false
  activation_quantize_type: moving_average_abs_max
  weight_quantize_type: channel_wise_abs_max
  not_quant_pattern:
  - skip_quant
  quantize_op_types:
  - conv2d
  - depthwise_conv2d
  weight_bits: 8
  
TrainConfig:
  epochs: 1
  eval_iter: 500
  learning_rate: 
    type: CosineAnnealingDecay 
    learning_rate: 0.015
  optimizer_builder:
    optimizer:
      type: Momentum
    weight_decay: 0.00002
  origin_metric: 0.7914
