input_list: ['image', 'scale_factor']
model_dir: ./picodet_s_416_coco_lcnet
model_filename: model.pdmodel
params_filename: model.pdiparams
save_dir: ./analysis_results
metric: COCO
num_classes: 80
plot_hist: True
get_target_quant_model: False
target_metric: None

PTQ:
  quantizable_op_type: ["conv2d", "depthwise_conv2d"]
  weight_quantize_type: 'abs_max'
  activation_quantize_type: 'moving_average_abs_max'
  is_full_quantize: False
  batch_size: 10
  batch_nums: 10

# Datset configuration
EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: /dataset/coco/

# Small Dataset to accelerate analysis
# If not exist, delete the dict of FastEvalDataset
# FastEvalDataset:
#   !COCODataSet
#     image_dir: val2017
#     anno_path: annotations/small_instances_val2017.json
#     dataset_dir: /dataset/coco/


eval_height: &eval_height 416
eval_width: &eval_width 416
eval_size: &eval_size [*eval_height, *eval_width]

worker_num: 0

EvalReader:
  inputs_def:
    image_shape: [1, 3, *eval_height, *eval_width]
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: *eval_size, keep_ratio: False}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_size: 1



