site_name: PaddleSlim Docs
repo_url: https://github.com/PaddlePaddle/PaddleSlim
nav:
- Home: index.md
- 模型库: model_zoo.md
- 教程:
  - 图像分类模型通道剪裁-快速开始: tutorials/pruning_tutorial.md
  - 图像分类模型离线量化-快速开始: tutorials/quant_post_tutorial.md
  - 图像分类模型量化训练-快速开始: tutorials/quant_aware_tutorial.md
  - Embedding量化: tutorials/quant_embedding_demo.md
  - SA搜索: tutorials/nas_demo.md
  - One-shot搜索: tutorials/one_shot_nas_demo.md
  - 搜索空间: search_space.md
  - 知识蒸馏: tutorials/distillation_demo.md
- API:
  - 量化: api/quantization_api.md
  - 剪枝与敏感度:  api/prune_api.md
  - 模型分析: api/analysis_api.md
  - 知识蒸馏: api/single_distiller_api.md
  - SA搜索: api/nas_api.md
  - One-shot搜索: api/one_shot_api.md
  - 搜索空间: search_space.md
  - 硬件延时评估表: table_latency.md
- 算法原理: algo/algo.md

theme:
    name: readthedocs
    highlightjs: true

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: "#"
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - mdx_math

extra_javascript:
  - mathjax-config.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
